/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_game_free: (a: number, b: number) => void;
export const game_add_player: (a: number, b: number) => void;
export const game_add_player_with_save: (a: number, b: number, c: number, d: number) => void;
export const game_apply_host_msg: (a: number, b: number, c: number, d: number) => void;
export const game_content_hash: (a: number) => bigint;
export const game_drain_audio: (a: number, b: number, c: number) => void;
export const game_drain_events_bytes: (a: number, b: number) => void;
export const game_drain_toasts: (a: number, b: number, c: number) => void;
export const game_encode_input: (a: number, b: number, c: number) => void;
export const game_encode_save_state: (a: number, b: number, c: number) => void;
export const game_encode_ui_action: (a: number, b: number, c: number, d: number) => void;
export const game_export_save: (a: number, b: number, c: number) => void;
export const game_handle_client_msg: (a: number, b: number, c: number, d: number) => void;
export const game_new: (a: number, b: number, c: number, d: bigint) => number;
export const game_player_screen: (a: number, b: number, c: number) => void;
export const game_remove_player: (a: number, b: number) => void;
export const game_render_frame: (a: number, b: number, c: number, d: number) => void;
export const game_set_input: (a: number, b: number, c: number) => void;
export const game_set_local_slot: (a: number, b: number) => void;
export const game_shop_json: (a: number, b: number, c: number, d: number) => void;
export const game_snapshot_bytes: (a: number, b: number) => void;
export const game_state_hash: (a: number) => bigint;
export const game_take_pending_save: (a: number, b: number) => void;
export const game_tick: (a: number) => void;
export const game_tick_count: (a: number) => number;
export const game_ui_action: (a: number, b: number, c: number, d: number) => void;
export const game_ui_state: (a: number, b: number, c: number) => void;
export const game_vendor_here: (a: number, b: number) => number;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export3: (a: number, b: number, c: number) => void;
